server:
  port: ${EVENT_SERVICE_PORT}
  tomcat:
    accept-count: 1000
    threads:
      max: 1000

spring:
  datasource:
    url: ${DB2_URL}
    username: ${DB2_USERNAME}
    password: ${DB2_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 100
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  application:
    name: event-service
  cloud: # 服务注册
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

myapp:
  allowed_ips: ${ALLOWED_IPS}