server:
  port: ${EVENT_SERVICE_PORT}

spring:
  datasource:
    url: ${DB2_URL}
    username: ${DB2_USERNAME}
    password: ${DB2_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  application:
    name: event-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}

myapp:
  user_server_ip: ${USER_SERVER_IP}