server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${ secrets.HOST_1 }:3306/timegenie?createDatabaseIfNotExist=true
    username: root
    password: ${ secrets.MYSQL_PASSWORD_1 }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  application:
    name: user-service
  cloud: # 服务注册
    nacos:
      discovery:
        server-addr: ${ secrets.HOST_1 }:8848