server:
  port: ${USER_SERVICE_PORT}
  tomcat:
    accept-count: 1000 # 服务端等待队列长度

spring:
  datasource:
    url: ${DB1_URL}
    username: ${DB1_USERNAME}
    password: ${DB1_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 100
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  application:
    name: user-service
  cloud: # 服务注册
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}