apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-1
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8301
          envFrom:
            - configMapRef:
                name: user-service-configmap
      nodeSelector:
        kubernetes.io/hostname: ecs-c9ec

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service-1
  namespace: user-service
spec:
  type: NodePort
  ports:
    - port: 30301
      targetPort: 8301
      nodePort: 30301
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-2
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8302
          envFrom:
            - configMapRef:
                name: user-service-configmap
      nodeSelector:
        kubernetes.io/hostname: ecs-c9ec

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service-2
  namespace: user-service
spec:
  type: NodePort
  ports:
    - port: 30302
      targetPort: 8302
      nodePort: 30302
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-3
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8303
          envFrom:
            - configMapRef:
                name: user-service-configmap
      nodeSelector:
        kubernetes.io/hostname: ecs-9c23

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service-3
  namespace: user-service
spec:
  type: NodePort
  ports:
    - port: 30303
      targetPort: 8303
      nodePort: 30303
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-4
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8304
          envFrom:
            - configMapRef:
                name: user-service-configmap
      nodeSelector:
        kubernetes.io/hostname: ecs-9c23

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service-4
  namespace: user-service
spec:
  type: NodePort
  ports:
    - port: 30304
      targetPort: 8304
      nodePort: 30304
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-5
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8305
          envFrom:
            - configMapRef:
                name: user-service-configmap
      nodeSelector:
        kubernetes.io/hostname: ecs-95b0

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service-5
  namespace: user-service
spec:
  type: NodePort
  ports:
    - port: 30305
      targetPort: 8305
      nodePort: 30305
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-6
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8306
          envFrom:
            - configMapRef:
                name: user-service-configmap
      nodeSelector:
        kubernetes.io/hostname: ecs-95b0

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service-6
  namespace: user-service
spec:
  type: NodePort
  ports:
    - port: 30306
      targetPort: 8306
      nodePort: 30306
  selector:
    app: user-service
