apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: user-service
spec:
  replicas: 6
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: user-service
          image: horizon12275/user-service-with-skywalking:latest
          ports:
            - containerPort: 8201
          envFrom:
            - configMapRef:
                name: user-service-configmap