name: Deploy with docker

on:
  push:
    # 分支
    branches:
      - SkywalkingTest
  pull_request:
    branches:
      - SkywalkingTest

jobs:
  SkywalkingTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      # maven缓存，不加的话每次都会去重新拉取，会影响速度
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 编译打包，传入环境变量参数
      - name: Build with Maven
        run: |
          cd ./code/backend
          mvn package \
              -Dmaven.test.skip=true \
      # 登录Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # build and push load-balance image
      - name: Build and push load-balance image
        id: docker_build_lb
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/jar/load-balance/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/load-balance-with-skywalking:latest
      # build and push user-service image
      - name: Build and push user-service image
        id: docker_build_user
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/jar/user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service-with-skywalking:latest
      # build and push event-service image
      - name: Build and push event-service image
        id: docker_build_event
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/jar/event-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/event-service-with-skywalking:latest
